# .github/dependabot.yml
version: 2
updates:
  # For GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Root of the repo
    schedule:
      interval: "weekly"

  # For npm (Node.js)
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "daily"

  # For pip (Python)
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt
    schedule:
      interval: "weekly"
