# Generated by Django 5.2 on 2025-04-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100)),
                ('toppings', models.EmailField(max_length=254)),
                ('quantity', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
