# Generated by Django 5.2 on 2025-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='special_instructions',
            field=models.TextField(default='No special instructions'),
        ),
    ]
